name: Deploy docker image on server

on:
  pull_request:

jobs:
  deploy:
  - name: Deploy to server
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SERVER_SECRET }}
      SERVER_IP: ${{ secrets.SERVER_URL }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_PAT: ${{ secrets.REGISTRY_PAT }}
      IMAGE_PATH: ${{ secrets.IMAGE_PATH }}
      DOCKER_NAME: grp-1-welcome_to_the_moon
      USER_NAME: ${{ secrets.USERNAME }}

    run: |
      echo "${{ env.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem -p ${{ env.SERVER_PORT }} ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << 'EOF'
            echo ${{ env.DOCKER_PAT }} | docker login ghcr.io -u ${{ env.USER_NAME }} --password-stdin
            docker stop ${{ env.DOCKER_NAME }} || true
            docker rm ${{ env.DOCKER_NAME }} || true
            docker pull ${{ env.IMAGE_PATH }}
            docker run -d --name ${{ env.DOCKER_NAME }} -p ${{ env.SERVER_PORT }}:${{ env.SERVER_PORT }} ${{ env.IMAGE_PATH }}
          EOF
          rm key.pem